server:
  port: 8081

spring:
  application:
    name: fraud
  datasource:
    username: 'branko'
    password: '602984'
    url: jdbc:postgresql://localhost:5432/fraud
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: create
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true